Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -8,45 +8,44 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Ensure required Gradle files are present
-      run: |
-        if [ ! -f "build.gradle" ] || [ ! -f "settings.gradle" ]; then
-          echo "Required Gradle files are missing"
-          exit 1
-        fi
+      - name: Ensure required Gradle files are present
+        run: |
+          if [ ! -f "build.gradle" ] || [ ! -f "settings.gradle" ]; then
+            echo "Required Gradle files are missing"
+            exit 1
+          fi
 
-    - name: Set up JDK 21
-      uses: actions/setup-java@v3
-      with:
-        java-version: '21'
-        distribution: 'temurin'
-        cache: gradle
+      - name: Set up JDK 21
+        uses: actions/setup-java@v3
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+          cache: gradle
 
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
 
-    - name: Build with Gradle
-      run: ./gradlew build
+      - name: Build with Gradle
+        run: ./gradlew build
 
-    - name: Run unit tests
-      run: ./gradlew test
+      - name: Run unit tests
+        run: ./gradlew test
 
-     - name: Set up environment variables for deployment
-      run: |
-        echo "DEPLOY_TO_PRODUCTION=${{ secrets.DEPLOY_TO_PRODUCTION }}" >> $GITHUB_ENV
-        echo "OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}" >> $GITHUB_ENV
-        echo "FREEASTROLOGYAPI_API_KEY=${{ secrets.FREEASTROLOGYAPI_API_KEY }}" >> $GITHUB_ENV
-        echo "HEALTH_API_KEY=${{ secrets.HEALTH_API_KEY }}" >> $GITHUB_ENV
-        echo "PORT=8000" >> $GITHUB_ENV
+      - name: Set up environment variables for deployment
+        run: |
+          echo "DEPLOY_TO_PRODUCTION=${{ secrets.DEPLOY_TO_PRODUCTION }}" >> $GITHUB_ENV
+          echo "OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}" >> $GITHUB_ENV
+          echo "FREEASTROLOGYAPI_API_KEY=${{ secrets.FREEASTROLOGYAPI_API_KEY }}" >> $GITHUB_ENV
+          echo "HEALTH_API_KEY=${{ secrets.HEALTH_API_KEY }}" >> $GITHUB_ENV
+          echo "PORT=8000" >> $GITHUB_ENV
 
-    - name: Deploy to production
-      if: env.DEPLOY_TO_PRODUCTION == 'true'
-      run: |
-        docker build -t cimeika-app .
-        docker run -d -p 8000:8000 --env-file .env cimeika-app
+      - name: Deploy to production
+        if: env.DEPLOY_TO_PRODUCTION == 'true'
+        run: |
+          docker build -t cimeika-app .
+          docker run -d -p 8000:8000 --env-file .env cimeika-app
